import type { Metadata } from "next";
import "./globals.css";

import { UseContext } from "@/context";
import { IBM_Plex_Sans_Thai } from "next/font/google";
import { Castoro } from "next/font/google";

import { ConfigProvider } from "antd";
import { AntdRegistry } from "@ant-design/nextjs-registry";

// ตั้งค่า IBM Plex Sans Thai
const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ["thai"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans-thai",
});

// ตั้งค่า Castoro
const castoro = Castoro({
  weight: "400",
  style: "italic",
  subsets: ["latin"],
  variable: "--font-castoro",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${ibmPlexSansThai.variable} ${castoro.variable} antialiased bg-gray-100 h-screen`}
      >
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#49A569", // ใช้สีเขียว
            },
          }}
        >
          <UseContext>
            <AntdRegistry>{children}</AntdRegistry>
          </UseContext>
        </ConfigProvider>
      </body>
    </html>
  );
}
